version: '3'
services:
  postgres:
    build: .
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=qwerty12345
    ports:
      - '5432:5432'
    volumes:
      - "./pgdata:/var/lib/postgresql/data"
      - "./backups:/mnt/backups"
